services:
  console:
    build:
      args:
        BUILDER_CONTAINER_IMAGE: python-builder
      context: components/console
    depends_on:
      - python-builder
    environment:
      SERVICE_PORT: 8080
      WORKER_URL: tcp://worker:5050
    ports:
      - 8080
  cpp-builder:
    image: cpp-builder
    build:
      context: components/cpp-builder
  monitor:
    build:
      args:
        BUILDER_CONTAINER_IMAGE: python-builder
      context: components/monitor
    depends_on:
      - python-builder
    environment:
      SERVICE_PORT: 8080
      MONITOR_PORT: 9090
    ports:
      - 8080
  python-builder:
    image: python-builder
    build:
      context: components/python-builder
  worker:
    build:
      args:
        BUILDER_CONTAINER_IMAGE: cpp-builder
      context: components/worker
    depends_on:
      - cpp-builder
    deploy:
      mode: replicated
      replicas: 2
    environment:
      MONITOR_URL: tcp://monitor:9090
      SERVICE_PORT: 5050
